### ISSUE TITLE
NumberFormatException in isim example

### ISSUE THREAD

**Issue by KasMA1990** [openivef/ivef-sdk#89]
I'm attempting to run the isim example as it is specified in the run_isim file (only paths changed) and I get the following error. I'm running Java 1.7.0_79.

java.lang.NumberFormatException: For input string: "IS-B158"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at ivef.Parser.startElement(Parser.java:634)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)

**Comment by KasMA1990** [comment]
Seems like the issue is with the test data; the standard expects the "Id" attributes of Tracks, VesselData, and VoyageData to only be integers, but as the stack trace shows, not all IDs are valid integers. Replacing the faulty IDs fixes the issue.
